### ISSUE TITLE
CMake organization

### ISSUE THREAD

**Issue by tdd11235813** [mYstar/McEA#1]
Hi

## CMake structure
it is recommended to use cmake in separate build|debug|release folders.
```bash
gpu/
- CMakeLists.txt
cpu/
- CMakeLists.txt
CMakeLists.txt  # calls add_subdirectory(gpu) ..
```
Adapt the paths so the workflow for making would be for instance:
```bash
mkdir debug
cd debug
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
# 
./app_gpu
./app_cpu
# or when separated sub folder is required
./cpu/app
./gpu/app
```

## CUDA Architectures and Fallback solution 

On compile nodes your SM arch finder does not help since there is no GPU on a compile node.
So you should provide a cmake option to set the CUDA architecture manually.

Furthermore, the cuda path variable cuda_root is not portable. You can check for a more integrated solution [here](https://github.com/BVLC/caffe/blob/master/cmake/Cuda.cmake). As of cmake 3.7 there also exists a [cmake function](https://cmake.org/cmake/help/v3.7/module/FindCUDA.html?highlight=cuda) `CUDA_SELECT_NVCC_ARCH_FLAGS` to detect and select architectures. But cmake 3.7 is still quite new so I would not make it as a minimal requirement.

Cheers

**Comment by mYstar** [comment]
do these commits solve the issue for you?

**Comment by tdd11235813** [comment]
sorry for my late reply, I check out your update as soon as possible.

**Comment by mYstar** [comment]
the pull request fixes all the issues for me

**Comment by tdd11235813** [comment]
agreed, thank you :)
