### ISSUE TITLE
cmake could not find config files and still continued

### ISSUE THREAD

**Issue by tdd11235813** [mYstar/McEA#3]
Hi

I had issues with [c]make'ing as the config files were not found, so I encountered invalid make targets, where the variables like `POP_WIDTH` haven't been substituted.
This helped me:
```
# instead of "../src/config/*.cmake" 
FILE(GLOB CONFIG_FILES "${CMAKE_CURRENT_SOURCE_DIR}/../config/*.cmake" )
```
I am working in `./release` instead of `./build/release`, but the cmake configuration should handle this.
Maybe you should check in cmake, if configs have been found though, otherwise abort cmake process.

**Comment by mYstar** [comment]
cpu CMake file had the same issue,
resolved in commit cdeccafbcd4b4d37a5a497dba207816473eb0d0a
